### ISSUE TITLE
JarJar Guava 

### ISSUE THREAD

**Issue by ejemba** [sonatype/sisu-guice#12]
I was wondering if the opportunity to jarjar the dependency Guava canno't be a great saver in many case.

Guava APi can change a lot from version to version and sometimes it can be tricky to compose with many version inside a full large project.

So jarjar it like you already did with 2 dependencies could help Guice adoption 

In our case it would help.

Regards,

**Comment by mcculls** [comment]
Originally google-collections (as it used to be called) was jarjar'd into Guice, but it was moved out as a separate dependency because Guava had grown to a large size causing bloat for people who already had a compatible version of Guava on their system. Since it was moved out as a separate dependency the APIs used by Guice (which are a small subset of Guava) have been very stable.

If someone does want to repackage Guava and Guice together they can always do that themselves (by following https://github.com/google/guava/wiki/UsingProGuardWithGuava). Going the opposite direction is always harder, and since there was popular demand to make Guava a first-class dependency I don't think this is something that will change in the future.

PS. the official Guice project can be found at https://github.com/google/guice - this is a patched build to try out various experimental features.
